name: Push to Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push Changes to Private Repo
        run: |
          git remote add private https://${{ secrets.GH_PAT }}@github.com/ZacksBot/GitBookBlackTekDocs.git
          git push private main
