name: Sync from Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Sync from Private Repo
      run: |
        git remote add source https://${{ secrets.GH_PAT }}@github.com/ZacksBot/GitBookBlackTekDocs.git
        git fetch source main
        git merge -X theirs source/main --allow-unrelated-histories -m "Merging changes from private repo"
        git push origin main
